### ISSUE TITLE
[BUG] safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by ZeyueT** [guyyariv/AudioToken#1]
Hi,
When I run the inference process, it has an error:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

Actually, when loading the Lora weight, there is a problem in 'self.unet.load_attn_procs(lora_layers_learned_embeds)' in the AudioToken.py
Are you sure the given Lora weight in the repo is the right file?

**Comment by divyanshusharma1709** [comment]
Hi @ZeyueT, did you solve this issue? Stuck on the same issue, but for the output file

**Comment by guyyariv** [comment]
Hey, thank you for letting me know. I'm checking it and will update you soon.

**Comment by guyyariv** [comment]
You're absolutely correct guys. The Lora weights uploaded to Git are corrupted, and unfortunately, I don't have a backup. Nevertheless, I've modified the default values to enable loading weights without Lora, the same as in the paper. Feel free to train with Lura; the training script now supports it. Remember to pull the latest changes.

Guy
