### ISSUE TITLE
Speech and Image Embeddings

### ISSUE THREAD

**Issue by lokesh12345678910** [guyyariv/AudioToken#3]
Given an audio file and an image, how can I use audioToken's pretrained model to derive an audio_feature_vector (i.e. speech embedding) and an image-feature-vector (i.e. image embedding)?

**Comment by guyyariv** [comment]
The pretrained model were trained on general audio and I'm not sure how it perform with speech. You can use our inference code with the pretrained weights for encoding audio signal into audio embedding, try use clip for image embedding.
