### ISSUE TITLE
Some details about how to inference

### ISSUE THREAD

**Issue by DthdZK** [guyyariv/AudioToken#4]
Dear Author, Is the test set in the inference.py the entire VGGSound dataset? I see that the code needs to use the dataloader of this dataset, so how do I implement it if I want to execute inference.py on any other audio?

**Comment by guyyariv** [comment]
Hello, and thanks for reaching out. I suggest making a copy of the dataloader class and adapting it for your audio files. In the current code, handling VGGSound , during inference, involves simply loading the audio files from a directory without any complex processing.

**Comment by DthdZK** [comment]
thanks a lot!
