### ISSUE TITLE
I cannot find any audio files of the VGGSound dataset

### ISSUE THREAD

**Issue by DthdZK** [guyyariv/AudioToken#5]
Dear Author, after I downloaded the VGGSound dataset from the huggingface connection you gave and unzipped it, I found that there is only video in it and no audio file, where should I download the corresponding audio file, without the audio file, I can't run the train.py

**Comment by guyyariv** [comment]
Hi, you can extract the audio files from the video files using this script: https://github.com/hche11/VGGSound/blob/master/preprocess_audio.py.

**Comment by DthdZK** [comment]
Thank you very much and wish you every success! @guyyariv

**Comment by guyyariv** [comment]
thanks :) good luck!
