### ISSUE TITLE
How to use "lora_layers_learned_embeds.bin" inference.py

### ISSUE THREAD

**Issue by DthdZK** [guyyariv/AudioToken#6]
Dear author, I see that train.py use LoRA, does this refer to fine-tuning the stable diffusion? And how to use the parameters of the trained LoRA layer in the inference.py? I would be grateful if you could give detailed examples and methods, and look forward to your reply, thanks!

**Comment by guyyariv** [comment]
Hi, LoRA indeed adds additional layers to the diffusion U-Net. The code supports training with LoRA and loading it when the LoRA flag is set to true. :)
