### ISSUE TITLE
Publish embedder_learned_embeds.bin for SD 2 (Feature/Request)

### ISSUE THREAD

**Issue by arielkantorovich** [guyyariv/AudioToken#7]
Hi, 
Thank you for the great work I will be glad if there is an option that you to publish embedded learned embeds.bin for stable diffusion 2.0V where the embedding space is in size 1024 instead of 768.

**Comment by guyyariv** [comment]
Hi, I'm currently preparing for NeurIPS and won't be able to run it. You can easily run it yourself by following the experimental details provided in the paper. Please send me the results if you manage to get them. Good luck! :)
