### ISSUE TITLE
Pretrained model(s)

### ISSUE THREAD

**Issue by darius522** [guyyariv/AudioToken#9]
Hi,

First off thank to the authors for this fantastic piece of work. 

I am currently working on a similar project and would like to possibly benchmark Audiotoken as part of our paper. would it be possible for the authors to make their pre-trained models publicly available ? I would like to avoid the extra compute tied with training everything from scratch, if possible.

Please let me know!

Darius

**Comment by guyyariv** [comment]
Hi Darius, good luck with your project :). The pretrained models are publicly available. Check out the Pre-Trained Embedder section in the README.

**Comment by darius522** [comment]
Hi Guy, I deeply apologize for missing that in the README. Thank you for the prompt reply and clarifications!

**Comment by darius522** [comment]
@guyyariv the following command is failing for me:

```
wget -O models/BEATs/BEATs_iter3_plus_AS2M_finetuned_on_AS2M_cpt2.pt "https://valle.blob.core.windows.net/share/BEATs/BEATs_iter3_plus_AS2M_finetuned_on_AS2M_cpt2.pt?sv=2020-08-04&st=2023-03-01T07%3A51%3A05Z&se=2033-03-02T07%3A51%3A00Z&sr=c&sp=rl&sig=QJXmSJG9DbMKf48UDIU1MfzIro8HQOf3sqlNXiflY1I%3D"
```

From which I get:
```
HTTP request sent, awaiting response... 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
2024-10-05 18:47:08 ERROR 403: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature..
```

I am  unsure if it is something on my end or not. Could you possibly check on your end to see if that link is indeed still valid ? Thank you in advance for your help!

**Comment by guyyariv** [comment]
Yes, I get this error as well; it seems like the link is broken. Instead, use this new official link: https://1drv.ms/u/s!AqeByhGUtINrgcpj8ujXH1YUtxooEg?e=E9Ncea (I got it from the original BEATS repo).

**Comment by darius522** [comment]
That works, thanks a bunch for your help!
